// ReSharper disable InconsistentNaming
namespace CSCore.Ffmpeg
{
    internal enum AVCodecID
    {
        AV_CODEC_ID_NONE,
        AV_CODEC_ID_MPEG1VIDEO,
        AV_CODEC_ID_MPEG2VIDEO,
        AV_CODEC_ID_MPEG2VIDEO_XVMC,
        AV_CODEC_ID_H261,
        AV_CODEC_ID_H263,
        AV_CODEC_ID_RV10,
        AV_CODEC_ID_RV20,
        AV_CODEC_ID_MJPEG,
        AV_CODEC_ID_MJPEGB,
        AV_CODEC_ID_LJPEG,
        AV_CODEC_ID_SP5X,
        AV_CODEC_ID_JPEGLS,
        AV_CODEC_ID_MPEG4,
        AV_CODEC_ID_RAWVIDEO,
        AV_CODEC_ID_MSMPEG4V1,
        AV_CODEC_ID_MSMPEG4V2,
        AV_CODEC_ID_MSMPEG4V3,
        AV_CODEC_ID_WMV1,
        AV_CODEC_ID_WMV2,
        AV_CODEC_ID_H263P,
        AV_CODEC_ID_H263I,
        AV_CODEC_ID_FLV1,
        AV_CODEC_ID_SVQ1,
        AV_CODEC_ID_SVQ3,
        AV_CODEC_ID_DVVIDEO,
        AV_CODEC_ID_HUFFYUV,
        AV_CODEC_ID_CYUV,
        AV_CODEC_ID_H264,
        AV_CODEC_ID_INDEO3,
        AV_CODEC_ID_VP3,
        AV_CODEC_ID_THEORA,
        AV_CODEC_ID_ASV1,
        AV_CODEC_ID_ASV2,
        AV_CODEC_ID_FFV1,
        AV_CODEC_ID_4XM,
        AV_CODEC_ID_VCR1,
        AV_CODEC_ID_CLJR,
        AV_CODEC_ID_MDEC,
        AV_CODEC_ID_ROQ,
        AV_CODEC_ID_INTERPLAY_VIDEO,
        AV_CODEC_ID_XAN_WC3,
        AV_CODEC_ID_XAN_WC4,
        AV_CODEC_ID_RPZA,
        AV_CODEC_ID_CINEPAK,
        AV_CODEC_ID_WS_VQA,
        AV_CODEC_ID_MSRLE,
        AV_CODEC_ID_MSVIDEO1,
        AV_CODEC_ID_IDCIN,
        AV_CODEC_ID_8BPS,
        AV_CODEC_ID_SMC,
        AV_CODEC_ID_FLIC,
        AV_CODEC_ID_TRUEMOTION1,
        AV_CODEC_ID_VMDVIDEO,
        AV_CODEC_ID_MSZH,
        AV_CODEC_ID_ZLIB,
        AV_CODEC_ID_QTRLE,
        AV_CODEC_ID_TSCC,
        AV_CODEC_ID_ULTI,
        AV_CODEC_ID_QDRAW,
        AV_CODEC_ID_VIXL,
        AV_CODEC_ID_QPEG,
        AV_CODEC_ID_PNG,
        AV_CODEC_ID_PPM,
        AV_CODEC_ID_PBM,
        AV_CODEC_ID_PGM,
        AV_CODEC_ID_PGMYUV,
        AV_CODEC_ID_PAM,
        AV_CODEC_ID_FFVHUFF,
        AV_CODEC_ID_RV30,
        AV_CODEC_ID_RV40,
        AV_CODEC_ID_VC1,
        AV_CODEC_ID_WMV3,
        AV_CODEC_ID_LOCO,
        AV_CODEC_ID_WNV1,
        AV_CODEC_ID_AASC,
        AV_CODEC_ID_INDEO2,
        AV_CODEC_ID_FRAPS,
        AV_CODEC_ID_TRUEMOTION2,
        AV_CODEC_ID_BMP,
        AV_CODEC_ID_CSCD,
        AV_CODEC_ID_MMVIDEO,
        AV_CODEC_ID_ZMBV,
        AV_CODEC_ID_AVS,
        AV_CODEC_ID_SMACKVIDEO,
        AV_CODEC_ID_NUV,
        AV_CODEC_ID_KMVC,
        AV_CODEC_ID_FLASHSV,
        AV_CODEC_ID_CAVS,
        AV_CODEC_ID_JPEG2000,
        AV_CODEC_ID_VMNC,
        AV_CODEC_ID_VP5,
        AV_CODEC_ID_VP6,
        AV_CODEC_ID_VP6F,
        AV_CODEC_ID_TARGA,
        AV_CODEC_ID_DSICINVIDEO,
        AV_CODEC_ID_TIERTEXSEQVIDEO,
        AV_CODEC_ID_TIFF,
        AV_CODEC_ID_GIF,
        AV_CODEC_ID_DXA,
        AV_CODEC_ID_DNXHD,
        AV_CODEC_ID_THP,
        AV_CODEC_ID_SGI,
        AV_CODEC_ID_C93,
        AV_CODEC_ID_BETHSOFTVID,
        AV_CODEC_ID_PTX,
        AV_CODEC_ID_TXD,
        AV_CODEC_ID_VP6A,
        AV_CODEC_ID_AMV,
        AV_CODEC_ID_VB,
        AV_CODEC_ID_PCX,
        AV_CODEC_ID_SUNRAST,
        AV_CODEC_ID_INDEO4,
        AV_CODEC_ID_INDEO5,
        AV_CODEC_ID_MIMIC,
        AV_CODEC_ID_RL2,
        AV_CODEC_ID_ESCAPE124,
        AV_CODEC_ID_DIRAC,
        AV_CODEC_ID_BFI,
        AV_CODEC_ID_CMV,
        AV_CODEC_ID_MOTIONPIXELS,
        AV_CODEC_ID_TGV,
        AV_CODEC_ID_TGQ,
        AV_CODEC_ID_TQI,
        AV_CODEC_ID_AURA,
        AV_CODEC_ID_AURA2,
        AV_CODEC_ID_V210X,
        AV_CODEC_ID_TMV,
        AV_CODEC_ID_V210,
        AV_CODEC_ID_DPX,
        AV_CODEC_ID_MAD,
        AV_CODEC_ID_FRWU,
        AV_CODEC_ID_FLASHSV2,
        AV_CODEC_ID_CDGRAPHICS,
        AV_CODEC_ID_R210,
        AV_CODEC_ID_ANM,
        AV_CODEC_ID_BINKVIDEO,
        AV_CODEC_ID_IFF_ILBM,
        AV_CODEC_ID_IFF_BYTERUN1,
        AV_CODEC_ID_KGV1,
        AV_CODEC_ID_YOP,
        AV_CODEC_ID_VP8,
        AV_CODEC_ID_PICTOR,
        AV_CODEC_ID_ANSI,
        AV_CODEC_ID_A64_MULTI,
        AV_CODEC_ID_A64_MULTI5,
        AV_CODEC_ID_R10K,
        AV_CODEC_ID_MXPEG,
        AV_CODEC_ID_LAGARITH,
        AV_CODEC_ID_PRORES,
        AV_CODEC_ID_JV,
        AV_CODEC_ID_DFA,
        AV_CODEC_ID_WMV3IMAGE,
        AV_CODEC_ID_VC1IMAGE,
        AV_CODEC_ID_UTVIDEO,
        AV_CODEC_ID_BMV_VIDEO,
        AV_CODEC_ID_VBLE,
        AV_CODEC_ID_DXTORY,
        AV_CODEC_ID_V410,
        AV_CODEC_ID_XWD,
        AV_CODEC_ID_CDXL,
        AV_CODEC_ID_XBM,
        AV_CODEC_ID_ZEROCODEC,
        AV_CODEC_ID_MSS1,
        AV_CODEC_ID_MSA1,
        AV_CODEC_ID_TSCC2,
        AV_CODEC_ID_MTS2,
        AV_CODEC_ID_CLLC,
        AV_CODEC_ID_MSS2,
        AV_CODEC_ID_VP9,
        AV_CODEC_ID_AIC,
        AV_CODEC_ID_ESCAPE130_DEPRECATED,
        AV_CODEC_ID_G2M_DEPRECATED,
        AV_CODEC_ID_WEBP_DEPRECATED,
        AV_CODEC_ID_HNM4_VIDEO,
        AV_CODEC_ID_HEVC_DEPRECATED,
        AV_CODEC_ID_FIC,
        AV_CODEC_ID_ALIAS_PIX,
        AV_CODEC_ID_BRENDER_PIX_DEPRECATED,
        AV_CODEC_ID_PAF_VIDEO_DEPRECATED,
        AV_CODEC_ID_EXR_DEPRECATED,
        AV_CODEC_ID_VP7_DEPRECATED,
        AV_CODEC_ID_SANM_DEPRECATED,
        AV_CODEC_ID_SGIRLE_DEPRECATED,
        AV_CODEC_ID_MVC1_DEPRECATED,
        AV_CODEC_ID_MVC2_DEPRECATED,
        AV_CODEC_ID_BRENDER_PIX = 0x42504958, // ((('X' | ('I' << 8)) | ('P' << 16)) | ('B' << 24))
        AV_CODEC_ID_Y41P = 0x59343150, // ((('P' | ('1' << 8)) | ('4' << 16)) | ('Y' << 24))
        AV_CODEC_ID_ESCAPE130 = 0x45313330, // ((('0' | ('3' << 8)) | ('1' << 16)) | ('E' << 24))
        AV_CODEC_ID_EXR = 0x30455852, // ((('R' | ('X' << 8)) | ('E' << 16)) | ('0' << 24))
        AV_CODEC_ID_AVRP = 0x41565250, // ((('P' | ('R' << 8)) | ('V' << 16)) | ('A' << 24))
        AV_CODEC_ID_012V = 0x30313256, // ((('V' | ('2' << 8)) | ('1' << 16)) | ('0' << 24))
        AV_CODEC_ID_G2M = 0x47324d, // ((('M' | ('2' << 8)) | ('G' << 16)) | (0 << 24))
        AV_CODEC_ID_AVUI = 0x41565549, // ((('I' | ('U' << 8)) | ('V' << 16)) | ('A' << 24))
        AV_CODEC_ID_AYUV = 0x41595556, // ((('V' | ('U' << 8)) | ('Y' << 16)) | ('A' << 24))
        AV_CODEC_ID_TARGA_Y216 = 0x54323136, // ((('6' | ('1' << 8)) | ('2' << 16)) | ('T' << 24))
        AV_CODEC_ID_V308 = 0x56333038, // ((('8' | ('0' << 8)) | ('3' << 16)) | ('V' << 24))
        AV_CODEC_ID_V408 = 0x56343038, // ((('8' | ('0' << 8)) | ('4' << 16)) | ('V' << 24))
        AV_CODEC_ID_YUV4 = 0x59555634, // ((('4' | ('V' << 8)) | ('U' << 16)) | ('Y' << 24))
        AV_CODEC_ID_SANM = 0x53414e4d, // ((('M' | ('N' << 8)) | ('A' << 16)) | ('S' << 24))
        AV_CODEC_ID_PAF_VIDEO = 0x50414656, // ((('V' | ('F' << 8)) | ('A' << 16)) | ('P' << 24))
        AV_CODEC_ID_AVRN = 0x4156526e, // ((('n' | ('R' << 8)) | ('V' << 16)) | ('A' << 24))
        AV_CODEC_ID_CPIA = 0x43504941, // ((('A' | ('I' << 8)) | ('P' << 16)) | ('C' << 24))
        AV_CODEC_ID_XFACE = 0x58464143, // ((('C' | ('A' << 8)) | ('F' << 16)) | ('X' << 24))
        AV_CODEC_ID_SGIRLE = 0x53474952, // ((('R' | ('I' << 8)) | ('G' << 16)) | ('S' << 24))
        AV_CODEC_ID_MVC1 = 0x4d564331, // ((('1' | ('C' << 8)) | ('V' << 16)) | ('M' << 24))
        AV_CODEC_ID_MVC2,
        AV_CODEC_ID_SNOW = 0x534e4f57, // ((('W' | ('O' << 8)) | ('N' << 16)) | ('S' << 24))
        AV_CODEC_ID_WEBP = 0x57454250, // ((('P' | ('B' << 8)) | ('E' << 16)) | ('W' << 24))
        AV_CODEC_ID_SMVJPEG = 0x534d564a, // ((('J' | ('V' << 8)) | ('M' << 16)) | ('S' << 24))
        AV_CODEC_ID_HEVC = 0x48323635, // ((('5' | ('6' << 8)) | ('2' << 16)) | ('H' << 24))
        AV_CODEC_ID_VP7 = 0x56503730, // ((('0' | ('7' << 8)) | ('P' << 16)) | ('V' << 24))
        AV_CODEC_ID_APNG = 0x41504e47, // ((('G' | ('N' << 8)) | ('P' << 16)) | ('A' << 24))
        AV_CODEC_ID_FIRST_AUDIO = 0x10000, // 65536
        AV_CODEC_ID_PCM_S16LE = 0x10000, // 65536
        AV_CODEC_ID_PCM_S16BE,
        AV_CODEC_ID_PCM_U16LE,
        AV_CODEC_ID_PCM_U16BE,
        AV_CODEC_ID_PCM_S8,
        AV_CODEC_ID_PCM_U8,
        AV_CODEC_ID_PCM_MULAW,
        AV_CODEC_ID_PCM_ALAW,
        AV_CODEC_ID_PCM_S32LE,
        AV_CODEC_ID_PCM_S32BE,
        AV_CODEC_ID_PCM_U32LE,
        AV_CODEC_ID_PCM_U32BE,
        AV_CODEC_ID_PCM_S24LE,
        AV_CODEC_ID_PCM_S24BE,
        AV_CODEC_ID_PCM_U24LE,
        AV_CODEC_ID_PCM_U24BE,
        AV_CODEC_ID_PCM_S24DAUD,
        AV_CODEC_ID_PCM_ZORK,
        AV_CODEC_ID_PCM_S16LE_PLANAR,
        AV_CODEC_ID_PCM_DVD,
        AV_CODEC_ID_PCM_F32BE,
        AV_CODEC_ID_PCM_F32LE,
        AV_CODEC_ID_PCM_F64BE,
        AV_CODEC_ID_PCM_F64LE,
        AV_CODEC_ID_PCM_BLURAY,
        AV_CODEC_ID_PCM_LXF,
        AV_CODEC_ID_S302M,
        AV_CODEC_ID_PCM_S8_PLANAR,
        AV_CODEC_ID_PCM_S24LE_PLANAR_DEPRECATED,
        AV_CODEC_ID_PCM_S32LE_PLANAR_DEPRECATED,
        AV_CODEC_ID_PCM_S24LE_PLANAR = 0x18505350, // ((('P' | ('S' << 8)) | ('P' << 16)) | (24 << 24))
        AV_CODEC_ID_PCM_S32LE_PLANAR = 0x20505350, // ((('P' | ('S' << 8)) | ('P' << 16)) | (32 << 24))
        AV_CODEC_ID_PCM_S16BE_PLANAR = 0x50535010, // (((16 | ('P' << 8)) | ('S' << 16)) | ('P' << 24))
        AV_CODEC_ID_ADPCM_IMA_QT = 0x11000, // 69632
        AV_CODEC_ID_ADPCM_IMA_WAV,
        AV_CODEC_ID_ADPCM_IMA_DK3,
        AV_CODEC_ID_ADPCM_IMA_DK4,
        AV_CODEC_ID_ADPCM_IMA_WS,
        AV_CODEC_ID_ADPCM_IMA_SMJPEG,
        AV_CODEC_ID_ADPCM_MS,
        AV_CODEC_ID_ADPCM_4XM,
        AV_CODEC_ID_ADPCM_XA,
        AV_CODEC_ID_ADPCM_ADX,
        AV_CODEC_ID_ADPCM_EA,
        AV_CODEC_ID_ADPCM_G726,
        AV_CODEC_ID_ADPCM_CT,
        AV_CODEC_ID_ADPCM_SWF,
        AV_CODEC_ID_ADPCM_YAMAHA,
        AV_CODEC_ID_ADPCM_SBPRO_4,
        AV_CODEC_ID_ADPCM_SBPRO_3,
        AV_CODEC_ID_ADPCM_SBPRO_2,
        AV_CODEC_ID_ADPCM_THP,
        AV_CODEC_ID_ADPCM_IMA_AMV,
        AV_CODEC_ID_ADPCM_EA_R1,
        AV_CODEC_ID_ADPCM_EA_R3,
        AV_CODEC_ID_ADPCM_EA_R2,
        AV_CODEC_ID_ADPCM_IMA_EA_SEAD,
        AV_CODEC_ID_ADPCM_IMA_EA_EACS,
        AV_CODEC_ID_ADPCM_EA_XAS,
        AV_CODEC_ID_ADPCM_EA_MAXIS_XA,
        AV_CODEC_ID_ADPCM_IMA_ISS,
        AV_CODEC_ID_ADPCM_G722,
        AV_CODEC_ID_ADPCM_IMA_APC,
        AV_CODEC_ID_ADPCM_VIMA_DEPRECATED,
        AV_CODEC_ID_ADPCM_VIMA = 0x56494d41, // ((('A' | ('M' << 8)) | ('I' << 16)) | ('V' << 24))
        AV_CODEC_ID_VIMA = 0x56494d41, // ((('A' | ('M' << 8)) | ('I' << 16)) | ('V' << 24))
        AV_CODEC_ID_ADPCM_AFC = 0x41464320, // (((' ' | ('C' << 8)) | ('F' << 16)) | ('A' << 24))
        AV_CODEC_ID_ADPCM_IMA_OKI = 0x4f4b4920, // (((' ' | ('I' << 8)) | ('K' << 16)) | ('O' << 24))
        AV_CODEC_ID_ADPCM_DTK = 0x44544b20, // (((' ' | ('K' << 8)) | ('T' << 16)) | ('D' << 24))
        AV_CODEC_ID_ADPCM_IMA_RAD = 0x52414420, // (((' ' | ('D' << 8)) | ('A' << 16)) | ('R' << 24))
        AV_CODEC_ID_ADPCM_G726LE = 0x36323747, // ((('G' | ('7' << 8)) | ('2' << 16)) | ('6' << 24))
        AV_CODEC_ID_AMR_NB = 0x12000, // 73728
        AV_CODEC_ID_AMR_WB,
        AV_CODEC_ID_RA_144 = 0x13000, // 77824
        AV_CODEC_ID_RA_288,
        AV_CODEC_ID_ROQ_DPCM = 0x14000, // 81920
        AV_CODEC_ID_INTERPLAY_DPCM,
        AV_CODEC_ID_XAN_DPCM,
        AV_CODEC_ID_SOL_DPCM,
        AV_CODEC_ID_MP2 = 0x15000, // 86016
        AV_CODEC_ID_MP3,
        AV_CODEC_ID_AAC,
        AV_CODEC_ID_AC3,
        AV_CODEC_ID_DTS,
        AV_CODEC_ID_VORBIS,
        AV_CODEC_ID_DVAUDIO,
        AV_CODEC_ID_WMAV1,
        AV_CODEC_ID_WMAV2,
        AV_CODEC_ID_MACE3,
        AV_CODEC_ID_MACE6,
        AV_CODEC_ID_VMDAUDIO,
        AV_CODEC_ID_FLAC,
        AV_CODEC_ID_MP3ADU,
        AV_CODEC_ID_MP3ON4,
        AV_CODEC_ID_SHORTEN,
        AV_CODEC_ID_ALAC,
        AV_CODEC_ID_WESTWOOD_SND1,
        AV_CODEC_ID_GSM,
        AV_CODEC_ID_QDM2,
        AV_CODEC_ID_COOK,
        AV_CODEC_ID_TRUESPEECH,
        AV_CODEC_ID_TTA,
        AV_CODEC_ID_SMACKAUDIO,
        AV_CODEC_ID_QCELP,
        AV_CODEC_ID_WAVPACK,
        AV_CODEC_ID_DSICINAUDIO,
        AV_CODEC_ID_IMC,
        AV_CODEC_ID_MUSEPACK7,
        AV_CODEC_ID_MLP,
        AV_CODEC_ID_GSM_MS,
        AV_CODEC_ID_ATRAC3,
        AV_CODEC_ID_VOXWARE,
        AV_CODEC_ID_APE,
        AV_CODEC_ID_NELLYMOSER,
        AV_CODEC_ID_MUSEPACK8,
        AV_CODEC_ID_SPEEX,
        AV_CODEC_ID_WMAVOICE,
        AV_CODEC_ID_WMAPRO,
        AV_CODEC_ID_WMALOSSLESS,
        AV_CODEC_ID_ATRAC3P,
        AV_CODEC_ID_EAC3,
        AV_CODEC_ID_SIPR,
        AV_CODEC_ID_MP1,
        AV_CODEC_ID_TWINVQ,
        AV_CODEC_ID_TRUEHD,
        AV_CODEC_ID_MP4ALS,
        AV_CODEC_ID_ATRAC1,
        AV_CODEC_ID_BINKAUDIO_RDFT,
        AV_CODEC_ID_BINKAUDIO_DCT,
        AV_CODEC_ID_AAC_LATM,
        AV_CODEC_ID_QDMC,
        AV_CODEC_ID_CELT,
        AV_CODEC_ID_G723_1,
        AV_CODEC_ID_G729,
        AV_CODEC_ID_8SVX_EXP,
        AV_CODEC_ID_8SVX_FIB,
        AV_CODEC_ID_BMV_AUDIO,
        AV_CODEC_ID_RALF,
        AV_CODEC_ID_IAC,
        AV_CODEC_ID_ILBC,
        AV_CODEC_ID_OPUS_DEPRECATED,
        AV_CODEC_ID_COMFORT_NOISE,
        AV_CODEC_ID_TAK_DEPRECATED,
        AV_CODEC_ID_METASOUND,
        AV_CODEC_ID_PAF_AUDIO_DEPRECATED,
        AV_CODEC_ID_ON2AVC,
        AV_CODEC_ID_FFWAVESYNTH = 0x46465753, // ((('S' | ('W' << 8)) | ('F' << 16)) | ('F' << 24))
        AV_CODEC_ID_SONIC = 0x534f4e43, // ((('C' | ('N' << 8)) | ('O' << 16)) | ('S' << 24))
        AV_CODEC_ID_SONIC_LS = 0x534f4e4c, // ((('L' | ('N' << 8)) | ('O' << 16)) | ('S' << 24))
        AV_CODEC_ID_PAF_AUDIO = 0x50414641, // ((('A' | ('F' << 8)) | ('A' << 16)) | ('P' << 24))
        AV_CODEC_ID_OPUS = 0x4f505553, // ((('S' | ('U' << 8)) | ('P' << 16)) | ('O' << 24))
        AV_CODEC_ID_TAK = 0x7442614b, // ((('K' | ('a' << 8)) | ('B' << 16)) | ('t' << 24))
        AV_CODEC_ID_EVRC = 0x73657663, // ((('c' | ('v' << 8)) | ('e' << 16)) | ('s' << 24))
        AV_CODEC_ID_SMV = 0x73736d76, // ((('v' | ('m' << 8)) | ('s' << 16)) | ('s' << 24))
        AV_CODEC_ID_DSD_LSBF = 0x4453444c, // ((('L' | ('D' << 8)) | ('S' << 16)) | ('D' << 24))
        AV_CODEC_ID_DSD_MSBF,
        AV_CODEC_ID_DSD_LSBF_PLANAR = 0x44534431, // ((('1' | ('D' << 8)) | ('S' << 16)) | ('D' << 24))
        AV_CODEC_ID_DSD_MSBF_PLANAR = 0x44534438, // ((('8' | ('D' << 8)) | ('S' << 16)) | ('D' << 24))
        AV_CODEC_ID_FIRST_SUBTITLE = 0x17000, // 94208
        AV_CODEC_ID_DVD_SUBTITLE = 0x17000, // 94208
        AV_CODEC_ID_DVB_SUBTITLE,
        AV_CODEC_ID_TEXT,
        AV_CODEC_ID_XSUB,
        AV_CODEC_ID_SSA,
        AV_CODEC_ID_MOV_TEXT,
        AV_CODEC_ID_HDMV_PGS_SUBTITLE,
        AV_CODEC_ID_DVB_TELETEXT,
        AV_CODEC_ID_SRT,
        AV_CODEC_ID_MICRODVD = 0x6d445644, // ((('D' | ('V' << 8)) | ('D' << 16)) | ('m' << 24))
        AV_CODEC_ID_EIA_608 = 0x63363038, // ((('8' | ('0' << 8)) | ('6' << 16)) | ('c' << 24))
        AV_CODEC_ID_JACOSUB = 0x4a535542, // ((('B' | ('U' << 8)) | ('S' << 16)) | ('J' << 24))
        AV_CODEC_ID_SAMI = 0x53414d49, // ((('I' | ('M' << 8)) | ('A' << 16)) | ('S' << 24))
        AV_CODEC_ID_REALTEXT = 0x52545854, // ((('T' | ('X' << 8)) | ('T' << 16)) | ('R' << 24))
        AV_CODEC_ID_STL = 0x5370544c, // ((('L' | ('T' << 8)) | ('p' << 16)) | ('S' << 24))
        AV_CODEC_ID_SUBVIEWER1 = 0x53625631, // ((('1' | ('V' << 8)) | ('b' << 16)) | ('S' << 24))
        AV_CODEC_ID_SUBVIEWER = 0x53756256, // ((('V' | ('b' << 8)) | ('u' << 16)) | ('S' << 24))
        AV_CODEC_ID_SUBRIP = 0x53526970, // ((('p' | ('i' << 8)) | ('R' << 16)) | ('S' << 24))
        AV_CODEC_ID_WEBVTT = 0x57565454, // ((('T' | ('T' << 8)) | ('V' << 16)) | ('W' << 24))
        AV_CODEC_ID_MPL2 = 0x4d504c32, // ((('2' | ('L' << 8)) | ('P' << 16)) | ('M' << 24))
        AV_CODEC_ID_VPLAYER = 0x56506c72, // ((('r' | ('l' << 8)) | ('P' << 16)) | ('V' << 24))
        AV_CODEC_ID_PJS = 0x50684a53, // ((('S' | ('J' << 8)) | ('h' << 16)) | ('P' << 24))
        AV_CODEC_ID_ASS = 0x41535320, // (((' ' | ('S' << 8)) | ('S' << 16)) | ('A' << 24))
        AV_CODEC_ID_FIRST_UNKNOWN = 0x18000, // 98304
        AV_CODEC_ID_TTF = 0x18000, // 98304
        AV_CODEC_ID_BINTEXT = 0x42545854, // ((('T' | ('X' << 8)) | ('T' << 16)) | ('B' << 24))
        AV_CODEC_ID_XBIN = 0x5842494e, // ((('N' | ('I' << 8)) | ('B' << 16)) | ('X' << 24))
        AV_CODEC_ID_IDF = 0x494446, // ((('F' | ('D' << 8)) | ('I' << 16)) | (0 << 24))
        AV_CODEC_ID_OTF = 0x4f5446, // ((('F' | ('T' << 8)) | ('O' << 16)) | (0 << 24))
        AV_CODEC_ID_SMPTE_KLV = 0x4b4c5641, // ((('A' | ('V' << 8)) | ('L' << 16)) | ('K' << 24))
        AV_CODEC_ID_DVD_NAV = 0x444e4156, // ((('V' | ('A' << 8)) | ('N' << 16)) | ('D' << 24))
        AV_CODEC_ID_TIMED_ID3 = 0x54494433, // ((('3' | ('D' << 8)) | ('I' << 16)) | ('T' << 24))
        AV_CODEC_ID_BIN_DATA = 0x44415441, // ((('A' | ('T' << 8)) | ('A' << 16)) | ('D' << 24))
        AV_CODEC_ID_PROBE = 0x19000, // 102400
        AV_CODEC_ID_MPEG2TS = 0x20000, // 131072
        AV_CODEC_ID_MPEG4SYSTEMS,
        AV_CODEC_ID_FFMETADATA = 0x21000, // 135168
        CODEC_ID_NONE = 0x0, // AV_CODEC_ID_NONE
        CODEC_ID_MPEG1VIDEO,
        CODEC_ID_MPEG2VIDEO,
        CODEC_ID_MPEG2VIDEO_XVMC,
        CODEC_ID_H261,
        CODEC_ID_H263,
        CODEC_ID_RV10,
        CODEC_ID_RV20,
        CODEC_ID_MJPEG,
        CODEC_ID_MJPEGB,
        CODEC_ID_LJPEG,
        CODEC_ID_SP5X,
        CODEC_ID_JPEGLS,
        CODEC_ID_MPEG4,
        CODEC_ID_RAWVIDEO,
        CODEC_ID_MSMPEG4V1,
        CODEC_ID_MSMPEG4V2,
        CODEC_ID_MSMPEG4V3,
        CODEC_ID_WMV1,
        CODEC_ID_WMV2,
        CODEC_ID_H263P,
        CODEC_ID_H263I,
        CODEC_ID_FLV1,
        CODEC_ID_SVQ1,
        CODEC_ID_SVQ3,
        CODEC_ID_DVVIDEO,
        CODEC_ID_HUFFYUV,
        CODEC_ID_CYUV,
        CODEC_ID_H264,
        CODEC_ID_INDEO3,
        CODEC_ID_VP3,
        CODEC_ID_THEORA,
        CODEC_ID_ASV1,
        CODEC_ID_ASV2,
        CODEC_ID_FFV1,
        CODEC_ID_4XM,
        CODEC_ID_VCR1,
        CODEC_ID_CLJR,
        CODEC_ID_MDEC,
        CODEC_ID_ROQ,
        CODEC_ID_INTERPLAY_VIDEO,
        CODEC_ID_XAN_WC3,
        CODEC_ID_XAN_WC4,
        CODEC_ID_RPZA,
        CODEC_ID_CINEPAK,
        CODEC_ID_WS_VQA,
        CODEC_ID_MSRLE,
        CODEC_ID_MSVIDEO1,
        CODEC_ID_IDCIN,
        CODEC_ID_8BPS,
        CODEC_ID_SMC,
        CODEC_ID_FLIC,
        CODEC_ID_TRUEMOTION1,
        CODEC_ID_VMDVIDEO,
        CODEC_ID_MSZH,
        CODEC_ID_ZLIB,
        CODEC_ID_QTRLE,
        CODEC_ID_TSCC,
        CODEC_ID_ULTI,
        CODEC_ID_QDRAW,
        CODEC_ID_VIXL,
        CODEC_ID_QPEG,
        CODEC_ID_PNG,
        CODEC_ID_PPM,
        CODEC_ID_PBM,
        CODEC_ID_PGM,
        CODEC_ID_PGMYUV,
        CODEC_ID_PAM,
        CODEC_ID_FFVHUFF,
        CODEC_ID_RV30,
        CODEC_ID_RV40,
        CODEC_ID_VC1,
        CODEC_ID_WMV3,
        CODEC_ID_LOCO,
        CODEC_ID_WNV1,
        CODEC_ID_AASC,
        CODEC_ID_INDEO2,
        CODEC_ID_FRAPS,
        CODEC_ID_TRUEMOTION2,
        CODEC_ID_BMP,
        CODEC_ID_CSCD,
        CODEC_ID_MMVIDEO,
        CODEC_ID_ZMBV,
        CODEC_ID_AVS,
        CODEC_ID_SMACKVIDEO,
        CODEC_ID_NUV,
        CODEC_ID_KMVC,
        CODEC_ID_FLASHSV,
        CODEC_ID_CAVS,
        CODEC_ID_JPEG2000,
        CODEC_ID_VMNC,
        CODEC_ID_VP5,
        CODEC_ID_VP6,
        CODEC_ID_VP6F,
        CODEC_ID_TARGA,
        CODEC_ID_DSICINVIDEO,
        CODEC_ID_TIERTEXSEQVIDEO,
        CODEC_ID_TIFF,
        CODEC_ID_GIF,
        CODEC_ID_DXA,
        CODEC_ID_DNXHD,
        CODEC_ID_THP,
        CODEC_ID_SGI,
        CODEC_ID_C93,
        CODEC_ID_BETHSOFTVID,
        CODEC_ID_PTX,
        CODEC_ID_TXD,
        CODEC_ID_VP6A,
        CODEC_ID_AMV,
        CODEC_ID_VB,
        CODEC_ID_PCX,
        CODEC_ID_SUNRAST,
        CODEC_ID_INDEO4,
        CODEC_ID_INDEO5,
        CODEC_ID_MIMIC,
        CODEC_ID_RL2,
        CODEC_ID_ESCAPE124,
        CODEC_ID_DIRAC,
        CODEC_ID_BFI,
        CODEC_ID_CMV,
        CODEC_ID_MOTIONPIXELS,
        CODEC_ID_TGV,
        CODEC_ID_TGQ,
        CODEC_ID_TQI,
        CODEC_ID_AURA,
        CODEC_ID_AURA2,
        CODEC_ID_V210X,
        CODEC_ID_TMV,
        CODEC_ID_V210,
        CODEC_ID_DPX,
        CODEC_ID_MAD,
        CODEC_ID_FRWU,
        CODEC_ID_FLASHSV2,
        CODEC_ID_CDGRAPHICS,
        CODEC_ID_R210,
        CODEC_ID_ANM,
        CODEC_ID_BINKVIDEO,
        CODEC_ID_IFF_ILBM,
        CODEC_ID_IFF_BYTERUN1,
        CODEC_ID_KGV1,
        CODEC_ID_YOP,
        CODEC_ID_VP8,
        CODEC_ID_PICTOR,
        CODEC_ID_ANSI,
        CODEC_ID_A64_MULTI,
        CODEC_ID_A64_MULTI5,
        CODEC_ID_R10K,
        CODEC_ID_MXPEG,
        CODEC_ID_LAGARITH,
        CODEC_ID_PRORES,
        CODEC_ID_JV,
        CODEC_ID_DFA,
        CODEC_ID_WMV3IMAGE,
        CODEC_ID_VC1IMAGE,
        CODEC_ID_UTVIDEO,
        CODEC_ID_BMV_VIDEO,
        CODEC_ID_VBLE,
        CODEC_ID_DXTORY,
        CODEC_ID_V410,
        CODEC_ID_XWD,
        CODEC_ID_CDXL,
        CODEC_ID_XBM,
        CODEC_ID_ZEROCODEC,
        CODEC_ID_MSS1,
        CODEC_ID_MSA1,
        CODEC_ID_TSCC2,
        CODEC_ID_MTS2,
        CODEC_ID_CLLC,
        CODEC_ID_Y41P = 0x59343150, // ((('P' | ('1' << 8)) | ('4' << 16)) | ('Y' << 24))
        CODEC_ID_ESCAPE130 = 0x45313330, // ((('0' | ('3' << 8)) | ('1' << 16)) | ('E' << 24))
        CODEC_ID_EXR = 0x30455852, // ((('R' | ('X' << 8)) | ('E' << 16)) | ('0' << 24))
        CODEC_ID_AVRP = 0x41565250, // ((('P' | ('R' << 8)) | ('V' << 16)) | ('A' << 24))
        CODEC_ID_G2M = 0x47324d, // ((('M' | ('2' << 8)) | ('G' << 16)) | (0 << 24))
        CODEC_ID_AVUI = 0x41565549, // ((('I' | ('U' << 8)) | ('V' << 16)) | ('A' << 24))
        CODEC_ID_AYUV = 0x41595556, // ((('V' | ('U' << 8)) | ('Y' << 16)) | ('A' << 24))
        CODEC_ID_V308 = 0x56333038, // ((('8' | ('0' << 8)) | ('3' << 16)) | ('V' << 24))
        CODEC_ID_V408 = 0x56343038, // ((('8' | ('0' << 8)) | ('4' << 16)) | ('V' << 24))
        CODEC_ID_YUV4 = 0x59555634, // ((('4' | ('V' << 8)) | ('U' << 16)) | ('Y' << 24))
        CODEC_ID_SANM = 0x53414e4d, // ((('M' | ('N' << 8)) | ('A' << 16)) | ('S' << 24))
        CODEC_ID_PAF_VIDEO = 0x50414656, // ((('V' | ('F' << 8)) | ('A' << 16)) | ('P' << 24))
        CODEC_ID_SNOW = 0x534e4f57, // AV_CODEC_ID_SNOW
        CODEC_ID_FIRST_AUDIO = 0x10000, // 65536
        CODEC_ID_PCM_S16LE = 0x10000, // 65536
        CODEC_ID_PCM_S16BE,
        CODEC_ID_PCM_U16LE,
        CODEC_ID_PCM_U16BE,
        CODEC_ID_PCM_S8,
        CODEC_ID_PCM_U8,
        CODEC_ID_PCM_MULAW,
        CODEC_ID_PCM_ALAW,
        CODEC_ID_PCM_S32LE,
        CODEC_ID_PCM_S32BE,
        CODEC_ID_PCM_U32LE,
        CODEC_ID_PCM_U32BE,
        CODEC_ID_PCM_S24LE,
        CODEC_ID_PCM_S24BE,
        CODEC_ID_PCM_U24LE,
        CODEC_ID_PCM_U24BE,
        CODEC_ID_PCM_S24DAUD,
        CODEC_ID_PCM_ZORK,
        CODEC_ID_PCM_S16LE_PLANAR,
        CODEC_ID_PCM_DVD,
        CODEC_ID_PCM_F32BE,
        CODEC_ID_PCM_F32LE,
        CODEC_ID_PCM_F64BE,
        CODEC_ID_PCM_F64LE,
        CODEC_ID_PCM_BLURAY,
        CODEC_ID_PCM_LXF,
        CODEC_ID_S302M,
        CODEC_ID_PCM_S8_PLANAR,
        CODEC_ID_ADPCM_IMA_QT = 0x11000, // 69632
        CODEC_ID_ADPCM_IMA_WAV,
        CODEC_ID_ADPCM_IMA_DK3,
        CODEC_ID_ADPCM_IMA_DK4,
        CODEC_ID_ADPCM_IMA_WS,
        CODEC_ID_ADPCM_IMA_SMJPEG,
        CODEC_ID_ADPCM_MS,
        CODEC_ID_ADPCM_4XM,
        CODEC_ID_ADPCM_XA,
        CODEC_ID_ADPCM_ADX,
        CODEC_ID_ADPCM_EA,
        CODEC_ID_ADPCM_G726,
        CODEC_ID_ADPCM_CT,
        CODEC_ID_ADPCM_SWF,
        CODEC_ID_ADPCM_YAMAHA,
        CODEC_ID_ADPCM_SBPRO_4,
        CODEC_ID_ADPCM_SBPRO_3,
        CODEC_ID_ADPCM_SBPRO_2,
        CODEC_ID_ADPCM_THP,
        CODEC_ID_ADPCM_IMA_AMV,
        CODEC_ID_ADPCM_EA_R1,
        CODEC_ID_ADPCM_EA_R3,
        CODEC_ID_ADPCM_EA_R2,
        CODEC_ID_ADPCM_IMA_EA_SEAD,
        CODEC_ID_ADPCM_IMA_EA_EACS,
        CODEC_ID_ADPCM_EA_XAS,
        CODEC_ID_ADPCM_EA_MAXIS_XA,
        CODEC_ID_ADPCM_IMA_ISS,
        CODEC_ID_ADPCM_G722,
        CODEC_ID_ADPCM_IMA_APC,
        CODEC_ID_VIMA = 0x56494d41, // ((('A' | ('M' << 8)) | ('I' << 16)) | ('V' << 24))
        CODEC_ID_AMR_NB = 0x12000, // 73728
        CODEC_ID_AMR_WB,
        CODEC_ID_RA_144 = 0x13000, // 77824
        CODEC_ID_RA_288,
        CODEC_ID_ROQ_DPCM = 0x14000, // 81920
        CODEC_ID_INTERPLAY_DPCM,
        CODEC_ID_XAN_DPCM,
        CODEC_ID_SOL_DPCM,
        CODEC_ID_MP2 = 0x15000, // 86016
        CODEC_ID_MP3,
        CODEC_ID_AAC,
        CODEC_ID_AC3,
        CODEC_ID_DTS,
        CODEC_ID_VORBIS,
        CODEC_ID_DVAUDIO,
        CODEC_ID_WMAV1,
        CODEC_ID_WMAV2,
        CODEC_ID_MACE3,
        CODEC_ID_MACE6,
        CODEC_ID_VMDAUDIO,
        CODEC_ID_FLAC,
        CODEC_ID_MP3ADU,
        CODEC_ID_MP3ON4,
        CODEC_ID_SHORTEN,
        CODEC_ID_ALAC,
        CODEC_ID_WESTWOOD_SND1,
        CODEC_ID_GSM,
        CODEC_ID_QDM2,
        CODEC_ID_COOK,
        CODEC_ID_TRUESPEECH,
        CODEC_ID_TTA,
        CODEC_ID_SMACKAUDIO,
        CODEC_ID_QCELP,
        CODEC_ID_WAVPACK,
        CODEC_ID_DSICINAUDIO,
        CODEC_ID_IMC,
        CODEC_ID_MUSEPACK7,
        CODEC_ID_MLP,
        CODEC_ID_GSM_MS,
        CODEC_ID_ATRAC3,
        CODEC_ID_VOXWARE,
        CODEC_ID_APE,
        CODEC_ID_NELLYMOSER,
        CODEC_ID_MUSEPACK8,
        CODEC_ID_SPEEX,
        CODEC_ID_WMAVOICE,
        CODEC_ID_WMAPRO,
        CODEC_ID_WMALOSSLESS,
        CODEC_ID_ATRAC3P,
        CODEC_ID_EAC3,
        CODEC_ID_SIPR,
        CODEC_ID_MP1,
        CODEC_ID_TWINVQ,
        CODEC_ID_TRUEHD,
        CODEC_ID_MP4ALS,
        CODEC_ID_ATRAC1,
        CODEC_ID_BINKAUDIO_RDFT,
        CODEC_ID_BINKAUDIO_DCT,
        CODEC_ID_AAC_LATM,
        CODEC_ID_QDMC,
        CODEC_ID_CELT,
        CODEC_ID_G723_1,
        CODEC_ID_G729,
        CODEC_ID_8SVX_EXP,
        CODEC_ID_8SVX_FIB,
        CODEC_ID_BMV_AUDIO,
        CODEC_ID_RALF,
        CODEC_ID_IAC,
        CODEC_ID_ILBC,
        CODEC_ID_FFWAVESYNTH = 0x46465753, // ((('S' | ('W' << 8)) | ('F' << 16)) | ('F' << 24))
        CODEC_ID_SONIC = 0x534f4e43, // ((('C' | ('N' << 8)) | ('O' << 16)) | ('S' << 24))
        CODEC_ID_SONIC_LS = 0x534f4e4c, // ((('L' | ('N' << 8)) | ('O' << 16)) | ('S' << 24))
        CODEC_ID_PAF_AUDIO = 0x50414641, // ((('A' | ('F' << 8)) | ('A' << 16)) | ('P' << 24))
        CODEC_ID_OPUS = 0x4f505553, // ((('S' | ('U' << 8)) | ('P' << 16)) | ('O' << 24))
        CODEC_ID_FIRST_SUBTITLE = 0x17000, // 94208
        CODEC_ID_DVD_SUBTITLE = 0x17000, // 94208
        CODEC_ID_DVB_SUBTITLE,
        CODEC_ID_TEXT,
        CODEC_ID_XSUB,
        CODEC_ID_SSA,
        CODEC_ID_MOV_TEXT,
        CODEC_ID_HDMV_PGS_SUBTITLE,
        CODEC_ID_DVB_TELETEXT,
        CODEC_ID_SRT,
        CODEC_ID_MICRODVD = 0x6d445644, // ((('D' | ('V' << 8)) | ('D' << 16)) | ('m' << 24))
        CODEC_ID_EIA_608 = 0x63363038, // ((('8' | ('0' << 8)) | ('6' << 16)) | ('c' << 24))
        CODEC_ID_JACOSUB = 0x4a535542, // ((('B' | ('U' << 8)) | ('S' << 16)) | ('J' << 24))
        CODEC_ID_SAMI = 0x53414d49, // ((('I' | ('M' << 8)) | ('A' << 16)) | ('S' << 24))
        CODEC_ID_REALTEXT = 0x52545854, // ((('T' | ('X' << 8)) | ('T' << 16)) | ('R' << 24))
        CODEC_ID_SUBVIEWER = 0x53756256, // ((('V' | ('b' << 8)) | ('u' << 16)) | ('S' << 24))
        CODEC_ID_FIRST_UNKNOWN = 0x18000, // 98304
        CODEC_ID_TTF = 0x18000, // 98304
        CODEC_ID_BINTEXT = 0x42545854, // ((('T' | ('X' << 8)) | ('T' << 16)) | ('B' << 24))
        CODEC_ID_XBIN = 0x5842494e, // ((('N' | ('I' << 8)) | ('B' << 16)) | ('X' << 24))
        CODEC_ID_IDF = 0x494446, // ((('F' | ('D' << 8)) | ('I' << 16)) | (0 << 24))
        CODEC_ID_OTF = 0x4f5446, // ((('F' | ('T' << 8)) | ('O' << 16)) | (0 << 24))
        CODEC_ID_PROBE = 0x19000, // 102400
        CODEC_ID_MPEG2TS = 0x20000, // 131072
        CODEC_ID_MPEG4SYSTEMS,
        CODEC_ID_FFMETADATA = 0x21000, // 135168
    }
}